spring:
  application:
    name: ad-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/ #本地host文件 127.0.0.1 server1

#需要所有的请求都进过网关，需要配置
#prefix 是前缀 经过这个网关的都有一个前缀
zuul:
  prefix: /imooc
  routes:     #定义路由信息，针对单个微服务
    sponsor:   #微服务名字
      path: /ad-sponsor/**  # 网关 去掉 prefix后还有一个前缀 是服务的名称
      serviceId: eureka-client-ad-sponsor  #微服务的名称
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false   #如果为true  /ad-sponsor/**  会去除/ad-sponsor 再请求